name: Trigger Binder Build

on:
  workflow_run:
    workflows: [Docker Image]
    types:
      - completed

  workflow_dispatch:

  schedule:
    - cron: 0 */24 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BINDER_URL: https://mybinder.org/v2/gh/lobis/geant4-python-application/HEAD

jobs:
  docker-image:
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify that the binder url is in the readme
        run: |
          cat README.md | grep -q "$BINDER_URL" || (echo "Binder URL not found in README"; exit 1)

      - name: Trigger the binder
        run: |
          curl -sSf -o /dev/null $BINDER_URL
