name: Build and Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-image:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to the GitHub Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_GITHUB_TOKEN }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: false
          tags: |
            ghcr.io/lobis/geant4:latest
          labels: |
            maintainer.name="Luis Antonio Obis Aparicio"
            maintainer.email="luis.antonio.obis@gmail.com"
            org.opencontainers.image.source="https://github.com/lobis/geant4-pythonic-application"

      - name: Test image
        run: |
          docker run --rm ghcr.io/lobis/geant4:latest -c 'from geant4 import Application; Application().setup_manager()'

      - name: Publish
        run: docker push ghcr.io/lobis/geant4:latest
