name: Wheels

on:
  workflow_dispatch:

jobs:
  sdist:
    name: Source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Build sdist
        run: |
          python -m pip install build
          python -m build --sdist .

      - uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz

  wheel:
    name: ${{ matrix.config.os }} ${{ matrix.config.arch }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: [{ os: ubuntu-latest, arch: x86_64 }]
        python-version: [3.11]
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache Geant4 Installation
        id: cache-geant4
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/geant4
          key: geant4-${{ matrix.geant4-version }}-${{ matrix.platform }}
          fail-on-cache-miss: true

      - uses: pypa/cibuildwheel@v2.16.2
        env:
          CIBW_ARCHS: ${{ matrix.config.arch }}
          CIBW_BEFORE_ALL_LINUX: |
            python3 -m pip install cmake
            git clone https://github.com/apache/xerces-c.git /tmp/xerces
            git -C /tmp/xerces checkout tags/v3.2.4
            cmake -B /tmp/xerces/build -S /tmp/xerces -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=OFF -Dnetwork-accessor=socket -Dtranscoder=iconv -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_C_FLAGS=-fPIC
            cmake --build /tmp/xerces/build -j$(nproc) --target install
            rm -rf /tmp/xerces

            git clone https://github.com/Geant4/geant4.git /tmp/geant4 --branch=v11.1.3 --depth=1
            cmake -B /tmp/geant4/build -S /tmp/geant4 -DCMAKE_CXX_STANDARD=20 -DCMAKE_BUILD_TYPE=Release -DGEANT4_USE_GDML=ON -DGEANT4_INSTALL_EXAMPLES=OFF -DGEANT4_INSTALL_DATA=OFF -DGEANT4_BUILD_TLS_MODEL=global-dynamic -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_C_FLAGS=-fPIC -DGEANT4_USE_SYSTEM_EXPAT=OFF -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF
            cmake --build /tmp/geant4/build -j$(nproc) --target install
            rm -rf /tmp/geant4

      - name: Upload Wheels
        uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*.whl
